// jf-tokens.jsx — JejuFlow design tokens (Evergreen Modern)

const EG = {
  surface: '#fcf9f2',
  surfaceDim: '#dcdad3',
  surfaceLow: '#f6f3ed',
  surfaceCt: '#f0eee7',
  surfaceHi: '#ebe8e1',
  surfaceHi2: '#e5e2dc',
  ink: '#1c1c18',
  ink2: '#444844',
  outline: '#757873',
  outlineV: '#c5c7c2',
  primary: '#4b6450',
  primaryC: '#daf7dd',
  onPrimaryC: '#334c3a',
  primaryDim: '#b1ceb5',
  secondary: '#7a5645',
  secondaryC: '#fdcdb7',
  onSecondaryC: '#603f2f',
  tertiary: '#a43d00',
  tertiaryC: '#ffece5',
  onTertiaryC: '#bb4700',
  inverseSurface: '#31312c',
  inverseOnSurface: '#f3f0ea',
};

const FONT_DISPLAY = '"Montserrat", -apple-system, system-ui, sans-serif';
const FONT_BODY = '"Inter", "Pretendard Variable", -apple-system, system-ui, sans-serif';
const FONT_MONO = '"JetBrains Mono", ui-monospace, monospace';

const WEATHERS = {
  sunny:  { tint: '#ffb597', sky1: '#fcf9f2', sky2: '#f7e9d0', glyph: '☀', label: { ko:'맑음', en:'Clear', ja:'晴れ', zh:'晴' }, temp: 22 },
  cloudy: { tint: '#c5c7c2', sky1: '#f6f3ed', sky2: '#dcdad3', glyph: '☁', label: { ko:'흐림', en:'Cloudy', ja:'曇り', zh:'多云' }, temp: 18 },
  rain:   { tint: '#7a8da0', sky1: '#eaeaea', sky2: '#cbd2d8', glyph: '☂', label: { ko:'비',   en:'Rain',   ja:'雨',   zh:'雨' }, temp: 16 },
  wind:   { tint: '#b1ceb5', sky1: '#eef3eb', sky2: '#cfd9cb', glyph: '↗', label: { ko:'강풍', en:'Windy',  ja:'強風', zh:'大风' }, temp: 14 },
};

const I18N = {
  ko: {
    appName: 'JejuFlow', tag: '렌터카 없는 제주, 흐름대로',
    home: '홈', explore: '탐색', route: '여정', settings: '설정',
    nowAt: '지금 제주시', flowFor: '오늘의 흐름', forIndoor: '실내', forOutdoor: '야외',
    becauseRain: '비가 와요. 실내에서 천천히.', becauseSun: '맑아요. 바깥이 좋겠어요.',
    becauseCloud: '구름이 많아요. 야외도 무난해요.', becauseWind: '바람이 강해요. 해안은 피하세요.',
    busIn: '분 후', minWalk: '분 도보', nextBus: '다음 버스',
    addToRoute: '여정에 추가', added: '추가됨', save: '저장', saved: '저장됨',
    busLine: (n)=>`${n}번`, kmDown: '거리순', spotsCount: (n)=>`${n}곳`,
    kindCoast: '해안', kindOreum: '오름', kindOlle: '올레', kindMuseum: '박물관',
    todayRoute: '오늘의 여정', leaveBy: '출발', walking: '도보', riding: '버스',
    languages: '언어', weather: '날씨', userType: '사용자 유형', notify: '알림',
    domestic: '국내 관광객', foreign: '외국인 관광객',
    swipeUp: '위로 스와이프해서 추가', tapForDetail: '탭하여 상세보기',
    timeline: '시간', region: '권역', kind: '유형',
    backToFlow: '흐름으로', mapView: '지도', listView: '목록',
    swipeHint: '드래그하여 시간 이동',
    distance: '거리', stops: '정류장', allDay: '하루 종일',
    seeAll: '전체 보기',
  },
  en: {
    appName: 'JejuFlow', tag: 'Jeju in flow — without a car',
    home: 'Home', explore: 'Explore', route: 'Route', settings: 'Settings',
    nowAt: 'Jeju City', flowFor: "Today's flow", forIndoor: 'Indoor', forOutdoor: 'Outdoor',
    becauseRain: "It's raining. Stay slow, stay in.", becauseSun: 'Clear skies. Go outside.',
    becauseCloud: 'Cloud cover. Outdoor still works.', becauseWind: 'Strong wind. Avoid the coast.',
    busIn: 'min', minWalk: 'min walk', nextBus: 'Next bus',
    addToRoute: 'Add to route', added: 'Added', save: 'Save', saved: 'Saved',
    busLine: (n)=>`Bus ${n}`, kmDown: 'by distance', spotsCount: (n)=>`${n} spots`,
    kindCoast: 'Coast', kindOreum: 'Oreum', kindOlle: 'Olle', kindMuseum: 'Museum',
    todayRoute: "Today's route", leaveBy: 'Leave', walking: 'Walk', riding: 'Bus',
    languages: 'Language', weather: 'Weather', userType: 'Visitor', notify: 'Alerts',
    domestic: 'Domestic', foreign: 'Foreign',
    swipeUp: 'Swipe up to add', tapForDetail: 'Tap for detail',
    timeline: 'Time', region: 'Region', kind: 'Kind',
    backToFlow: 'Back to flow', mapView: 'Map', listView: 'List',
    swipeHint: 'Drag to shift time',
    distance: 'Distance', stops: 'Stops', allDay: 'All day',
    seeAll: 'See all',
  },
  ja: {
    appName: 'JejuFlow', tag: '車なしの済州、流れのままに',
    home: 'ホーム', explore: '探索', route: 'ルート', settings: '設定',
    nowAt: '済州市', flowFor: '今日の流れ', forIndoor: '室内', forOutdoor: '屋外',
    becauseRain: '雨です。ゆっくり室内で。', becauseSun: '晴れ。外へどうぞ。',
    becauseCloud: '曇りです。屋外も大丈夫。', becauseWind: '風が強い。海岸は避けて。',
    busIn: '分', minWalk: '分歩', nextBus: '次のバス',
    addToRoute: 'ルートに追加', added: '追加済', save: '保存', saved: '保存済',
    busLine: (n)=>`${n}番`, kmDown: '距離順', spotsCount: (n)=>`${n}ヶ所`,
    kindCoast: '海岸', kindOreum: 'オルム', kindOlle: 'オルレ', kindMuseum: '博物館',
    todayRoute: '今日のルート', leaveBy: '出発', walking: '徒歩', riding: 'バス',
    languages: '言語', weather: '天気', userType: '訪問者', notify: '通知',
    domestic: '国内', foreign: '外国人',
    swipeUp: '上にスワイプで追加', tapForDetail: 'タップで詳細',
    timeline: '時間', region: '地域', kind: '種類',
    backToFlow: '流れへ戻る', mapView: '地図', listView: 'リスト',
    swipeHint: 'ドラッグで時間移動',
    distance: '距離', stops: '停留所', allDay: '終日',
    seeAll: 'すべて表示',
  },
  zh: {
    appName: 'JejuFlow', tag: '无需租车,顺流游济州',
    home: '首页', explore: '探索', route: '路线', settings: '设置',
    nowAt: '济州市', flowFor: '今日之流', forIndoor: '室内', forOutdoor: '户外',
    becauseRain: '在下雨。慢慢呆在室内。', becauseSun: '晴天。出去走走。',
    becauseCloud: '多云。户外也合适。', becauseWind: '风大。请避开海岸。',
    busIn: '分钟', minWalk: '分钟步行', nextBus: '下一班',
    addToRoute: '加入路线', added: '已添加', save: '收藏', saved: '已收藏',
    busLine: (n)=>`${n}路`, kmDown: '按距离', spotsCount: (n)=>`${n}处`,
    kindCoast: '海岸', kindOreum: '岳', kindOlle: '偶来路', kindMuseum: '博物馆',
    todayRoute: '今日路线', leaveBy: '出发', walking: '步行', riding: '公交',
    languages: '语言', weather: '天气', userType: '访客', notify: '通知',
    domestic: '国内', foreign: '外国人',
    swipeUp: '上滑添加', tapForDetail: '点击查看',
    timeline: '时间', region: '地区', kind: '类型',
    backToFlow: '返回流', mapView: '地图', listView: '列表',
    swipeHint: '拖动切换时间',
    distance: '距离', stops: '站点', allDay: '全天',
    seeAll: '查看全部',
  },
};

// 12 spots
const SPOTS = [
  { id: 'hyeopjae',  region: 'hallim',   kind: 'coast',  indoor: false, walk: 4,  busLine: 202, busIn: 7,  hours: '09–18',
    name: { ko:'협재해수욕장', en:'Hyeopjae Beach', ja:'挾才ビーチ', zh:'挾才海水浴场' },
    blurb:{ ko:'에메랄드빛 수심이 얕은 해변', en:'Emerald shallows, white sand', ja:'エメラルドの浅瀬', zh:'翡翠色浅滩' },
    pos: { x: 18, y: 38 } },
  { id: 'gimnyeong', region: 'gujwa',    kind: 'coast',  indoor: false, walk: 6,  busLine: 201, busIn: 12, hours: '24h',
    name: { ko:'김녕 해변',     en:'Gimnyeong Beach',    ja:'金寧ビーチ',    zh:'金宁海滩' },
    blurb:{ ko:'한적한 동쪽 해안', en:'Quiet east coast', ja:'静かな東海岸', zh:'宁静东海岸' },
    pos: { x: 76, y: 22 } },
  { id: 'seongsan',  region: 'seongsan', kind: 'oreum',  indoor: false, walk: 8,  busLine: 201, busIn: 4,  hours: '07–20',
    name: { ko:'성산일출봉',    en:'Seongsan Ilchulbong', ja:'城山日出峰',   zh:'城山日出峰' },
    blurb:{ ko:'유네스코 일출 명소', en:'UNESCO sunrise peak', ja:'日の出の名所', zh:'日出胜地' },
    pos: { x: 88, y: 36 } },
  { id: 'manjang',   region: 'gujwa',    kind: 'museum', indoor: true,  walk: 12, busLine: 990, busIn: 18, hours: '09–17',
    name: { ko:'만장굴',        en:'Manjanggul Cave',    ja:'万丈窟',       zh:'万丈窟' },
    blurb:{ ko:'세계 최장 용암동굴', en:'Longest lava tube', ja:'世界最長の溶岩洞', zh:'世界最长熔岩洞' },
    pos: { x: 72, y: 32 } },
  { id: 'folkmuseum',region: 'jejusi',   kind: 'museum', indoor: true,  walk: 3,  busLine: 312, busIn: 6,  hours: '09–18',
    name: { ko:'국립제주박물관',en:'Jeju National Museum',ja:'国立済州博物館',zh:'国立济州博物馆' },
    blurb:{ ko:'제주 역사·문화', en:'Jeju heritage', ja:'済州の歴史', zh:'济州历史' },
    pos: { x: 42, y: 18 } },
  { id: 'olle7',     region: 'seogwipo', kind: 'olle',   indoor: false, walk: 2,  busLine: 281, busIn: 9,  hours: '24h',
    name: { ko:'올레 7코스',    en:'Olle Trail #7',      ja:'オルレ7コース', zh:'偶来7号' },
    blurb:{ ko:'외돌개 해안 산책', en:'Oedolgae cliffs', ja:'外石浦海岸', zh:'外石浦海岸' },
    pos: { x: 38, y: 78 } },
  { id: 'arteum',    region: 'aewol',    kind: 'museum', indoor: true,  walk: 5,  busLine: 251, busIn: 14, hours: '10–20',
    name: { ko:'아르떼뮤지엄',  en:'Arte Museum',         ja:'アルテミュージアム', zh:'Arte博物馆' },
    blurb:{ ko:'몰입형 미디어아트', en:'Immersive media art', ja:'没入型メディアアート', zh:'沉浸式媒体艺术' },
    pos: { x: 24, y: 28 } },
  { id: 'sanbang',   region: 'seogwipo', kind: 'oreum',  indoor: false, walk: 7,  busLine: 752, busIn: 11, hours: '08–18',
    name: { ko:'산방산',        en:'Sanbangsan',          ja:'山房山',       zh:'山房山' },
    blurb:{ ko:'남해를 품은 종 모양 산', en:'Bell-shaped mountain', ja:'鐘型の山', zh:'钟形山峰' },
    pos: { x: 28, y: 76 } },
  { id: 'cafe-bomnal', region: 'aewol', kind: 'cafe', indoor: true, walk: 3, busLine: 251, busIn: 8, hours: '10–22',
    name: { ko:'봄날 카페', en:'Bomnal Cafe', ja:'春の日カフェ', zh:'春日咖啡' },
    blurb:{ ko:'드라마 촬영지 오션뷰', en:'Famed ocean-view cafe', ja:'海の見えるカフェ', zh:'海景咖啡' },
    pos: { x: 22, y: 30 } },
  { id: 'dongmun',   region: 'jejusi',   kind: 'museum', indoor: true,  walk: 1,  busLine: 311, busIn: 3,  hours: '08–22',
    name: { ko:'동문시장',      en:'Dongmun Market',     ja:'東門市場',     zh:'东门市场' },
    blurb:{ ko:'재래시장·먹거리', en:'Local food market', ja:'伝統市場', zh:'传统市场' },
    pos: { x: 46, y: 16 } },
  { id: 'hallasan',  region: 'jejusi',   kind: 'oreum',  indoor: false, walk: 18, busLine: 240, busIn: 22, hours: '06–13',
    name: { ko:'한라산',        en:'Hallasan',           ja:'漢拏山',       zh:'汉拿山' },
    blurb:{ ko:'한국 최고봉', en:"Korea's highest peak", ja:'韓国最高峰', zh:'韩国最高峰' },
    pos: { x: 50, y: 50 } },
  { id: 'jusangjeolli', region: 'seogwipo', kind: 'coast', indoor: false, walk: 5, busLine: 752, busIn: 6, hours: '09–18',
    name: { ko:'주상절리', en:'Jusangjeolli Cliff', ja:'柱状節理', zh:'柱状节理' },
    blurb:{ ko:'육각 현무암 절벽', en:'Hexagonal basalt cliffs', ja:'六角形玄武岩', zh:'六角玄武岩' },
    pos: { x: 32, y: 82 } },
];

Object.assign(window, { EG, FONT_DISPLAY, FONT_BODY, FONT_MONO, WEATHERS, I18N, SPOTS });
