import '../models/spot.dart';

const List<Map<String, dynamic>> kSpotsRaw = [
  {
    'id': 'seongsan-ilchulbong',
    'name_en': 'Seongsan Sunrise Peak',
    'emoji': '',
    'sub': 'UNESCO volcanic crater',
    'category': 'outdoor',
    'region': 'seogwipo',
    'nearestStop': 'Seongsan Ilchulbong Entrance',
    'stopId': 'JEB406000816',
    'busRoutes': ['201', '211'],
    'walkMinutes': 5,
    'busWaitMinutes': 5,
    'bgColor': 0xFF2A1C08,
    'accentColor': 0xFFD4922A,
    'fee': 5000,
    'hours': '07:00-20:00',
    'tags': ['UNESCO', 'sunrise', 'volcanic'],
    'altSpotId': 'aqua-planet',
    'contentId': '126435',
    'lat': 33.4580,
    'lng': 126.9425,
  },
  {
    'id': 'hallim-park',
    'name_en': 'Hallim Park',
    'emoji': '',
    'sub': 'Subtropical garden and caves',
    'category': 'both',
    'region': 'jeju-city',
    'nearestStop': 'Hallim Park',
    'stopId': 'JEB405001253',
    'busRoutes': ['202', '784-1'],
    'walkMinutes': 3,
    'busWaitMinutes': 21,
    'bgColor': 0xFF0E2410,
    'accentColor': 0xFF4E9848,
    'fee': 14000,
    'hours': '08:30-18:00',
    'tags': ['garden', 'cave', 'family'],
    'altSpotId': 'manjanggul-cave',
    'contentId': '126455',
    'lat': 33.3977,
    'lng': 126.2497,
  },
  {
    'id': 'manjanggul-cave',
    'name_en': 'Manjanggul Lava Tube',
    'emoji': '',
    'sub': "One of the world's longest lava tubes",
    'category': 'indoor',
    'region': 'jeju-city',
    'nearestStop': 'Manjanggul Cave',
    'stopId': 'JEB405001338',
    'busRoutes': ['201'],
    'walkMinutes': 2,
    'busWaitMinutes': 18,
    'bgColor': 0xFF160C1C,
    'accentColor': 0xFF8A58A8,
    'fee': 4000,
    'hours': '09:00-18:00',
    'tags': ['indoor', 'cool', 'rain_ok', 'UNESCO'],
    'altSpotId': null,
    'contentId': '',
    'lat': 33.5284,
    'lng': 126.7714,
  },
  {
    'id': 'cheonjiyeon-falls',
    'name_en': 'Cheonjiyeon Waterfall',
    'emoji': '',
    'sub': 'Night-friendly waterfall walk',
    'category': 'outdoor',
    'region': 'seogwipo',
    'nearestStop': 'Cheonjiyeon Waterfall Entrance',
    'stopId': 'JEB406000414',
    'busRoutes': ['880'],
    'walkMinutes': 4,
    'busWaitMinutes': 7,
    'bgColor': 0xFF082030,
    'accentColor': 0xFF2898C0,
    'fee': 0,
    'hours': '09:00-22:00',
    'tags': ['waterfall', 'free', 'nature'],
    'altSpotId': 'haenyeo-museum',
    'contentId': '126438',
    'lat': 33.2468,
    'lng': 126.5609,
  },
  {
    'id': 'hyeopjae-beach',
    'name_en': 'Hyeopjae Beach',
    'emoji': '',
    'sub': 'Emerald water and white sand',
    'category': 'outdoor',
    'region': 'jeju-city',
    'nearestStop': 'Hyeopjae Beach',
    'stopId': 'JEB405001251',
    'busRoutes': ['202'],
    'walkMinutes': 3,
    'busWaitMinutes': 19,
    'bgColor': 0xFF062232,
    'accentColor': 0xFF00B8A8,
    'fee': 0,
    'hours': 'All day',
    'tags': ['beach', 'free', 'swimming'],
    'altSpotId': 'manjanggul-cave',
    'contentId': '127490',
    'lat': 33.3939,
    'lng': 126.2393,
  },
  {
    'id': 'seopjikoji',
    'name_en': 'Seopjikoji Cape',
    'emoji': '',
    'sub': 'Canola fields and lighthouse',
    'category': 'outdoor',
    'region': 'seogwipo',
    'nearestStop': 'Seopjikoji',
    'stopId': 'JEB406001406',
    'busRoutes': ['295'],
    'walkMinutes': 8,
    'busWaitMinutes': 35,
    'bgColor': 0xFF201800,
    'accentColor': 0xFFC8A018,
    'fee': 0,
    'hours': 'All day',
    'tags': ['scenic', 'free', 'walking', 'lighthouse'],
    'altSpotId': 'haenyeo-museum',
    'contentId': '127813',
    'lat': 33.4318,
    'lng': 126.9301,
  },
  {
    'id': 'haenyeo-museum',
    'name_en': 'Haenyeo Museum',
    'emoji': '',
    'sub': 'Female diver culture and UNESCO heritage',
    'category': 'indoor',
    'region': 'seogwipo',
    'nearestStop': 'Haenyeo Museum',
    'stopId': 'JEB405001957',
    'busRoutes': ['260'],
    'walkMinutes': 1,
    'busWaitMinutes': 14,
    'bgColor': 0xFF08141E,
    'accentColor': 0xFF2878B0,
    'fee': 1100,
    'hours': '09:00-18:00',
    'tags': ['indoor', 'culture', 'rain_ok', 'UNESCO'],
    'altSpotId': null,
    'contentId': '130857',
    'lat': 33.3592,
    'lng': 126.8699,
  },
  {
    'id': 'bijarim-forest',
    'name_en': 'Bijarim Forest',
    'emoji': '',
    'sub': 'Ancient nutmeg grove',
    'category': 'outdoor',
    'region': 'jeju-city',
    'nearestStop': 'Bijarim Forest',
    'stopId': 'JEB405000852',
    'busRoutes': ['260'],
    'walkMinutes': 4,
    'busWaitMinutes': 22,
    'bgColor': 0xFF101A08,
    'accentColor': 0xFF70982C,
    'fee': 0,
    'hours': '09:00-17:00',
    'tags': ['forest', 'free', 'nature', 'walking'],
    'altSpotId': 'manjanggul-cave',
    'contentId': '',
    'lat': 33.5034,
    'lng': 126.7978,
  },
  {
    'id': 'aqua-planet',
    'name_en': 'Aqua Planet Jeju',
    'emoji': '',
    'sub': "Korea's largest aquarium",
    'category': 'indoor',
    'region': 'seogwipo',
    'nearestStop': 'Seongsan Port Entrance',
    'stopId': 'JEB406000822',
    'busRoutes': ['201', '211', '212', '295'],
    'walkMinutes': 7,
    'busWaitMinutes': 5,
    'bgColor': 0xFF041018,
    'accentColor': 0xFF0870C0,
    'fee': 36400,
    'hours': '10:00-19:00',
    'tags': ['indoor', 'rain_ok', 'aquarium', 'family'],
    'altSpotId': null,
    'contentId': '2048059',
    'lat': 33.4604,
    'lng': 126.9341,
  },
  {
    'id': 'eco-land',
    'name_en': 'Eco Land Theme Park',
    'emoji': '',
    'sub': 'Train through Gotjawal forest',
    'category': 'both',
    'region': 'jeju-city',
    'nearestStop': 'Jeju Stone Park',
    'stopId': 'JEB405001375',
    'busRoutes': ['131', '701-1', '701-2'],
    'walkMinutes': 1,
    'busWaitMinutes': 15,
    'bgColor': 0xFF0E1C08,
    'accentColor': 0xFF58A030,
    'fee': 14000,
    'hours': '08:30-18:00',
    'tags': ['family', 'forest', 'train'],
    'altSpotId': null,
    'contentId': '1146121',
    'lat': 33.4877,
    'lng': 126.7461,
  },
  {
    'id': 'yongduam-rock',
    'name_en': 'Yongduam Dragon Head Rock',
    'emoji': '',
    'sub': 'Volcanic rock near Jeju Port',
    'category': 'outdoor',
    'region': 'jeju-city',
    'nearestStop': 'Yongduam Hyundai Apt',
    'stopId': 'JEB405002117',
    'busRoutes': ['432'],
    'walkMinutes': 5,
    'busWaitMinutes': 12,
    'bgColor': 0xFF0C0C0E,
    'accentColor': 0xFF7890A8,
    'fee': 0,
    'hours': 'All day',
    'tags': ['scenic', 'free', 'coastal', 'photo'],
    'altSpotId': 'manjanggul-cave',
    'contentId': '228853',
    'lat': 33.5164,
    'lng': 126.5086,
  },
  {
    'id': 'sangumburi',
    'name_en': 'Sangumburi Crater',
    'emoji': '',
    'sub': 'Dormant crater with open grasslands',
    'category': 'outdoor',
    'region': 'jeju-city',
    'nearestStop': 'Sangumburi',
    'stopId': 'JEB405001177',
    'busRoutes': ['212'],
    'walkMinutes': 5,
    'busWaitMinutes': 25,
    'bgColor': 0xFF1A1408,
    'accentColor': 0xFFC09038,
    'fee': 3000,
    'hours': '08:30-17:30',
    'tags': ['nature', 'crater', 'walking'],
    'altSpotId': 'manjanggul-cave',
    'contentId': '126474',
    'lat': 33.4397,
    'lng': 126.7703,
  },
];

final kSpots = kSpotsRaw.map(Spot.fromMap).toList();
final kSpotById = {for (final s in kSpots) s.id: s};
